# -*- coding: utf-8 -*-
"""Split

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RIHdgNO16OLFo1qptwxvkjvpm2C8w7Ed
"""

import cv2
import os
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

def split_video(input_path, split_time_minutes, split_time_seconds):
    cap = cv2.VideoCapture(input_path)

    if not cap.isOpened():
        print("Error: Could not open video file.")
        return

    fps = int(cap.get(cv2.CAP_PROP_FPS))
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    fourcc = cv2.VideoWriter_fourcc(*'H264')

    output_folder = os.path.dirname(input_path)
    output_file_prefix = os.path.splitext(os.path.basename(input_path))[0]

    split_frame = int((split_time_minutes * 60 + split_time_seconds) * fps)

    frame_count = 0
    output_index = 1

    out = cv2.VideoWriter(os.path.join(output_folder, f"{output_file_prefix}_part{output_index}.mp4"), fourcc, fps, (width, height))

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        frame_count += 1
        out.write(frame)

        if frame_count >= split_frame or frame_count == total_frames:
            out.release()
            output_index += 1
            if frame_count < total_frames:
                out = cv2.VideoWriter(os.path.join(output_folder, f"{output_file_prefix}_part{output_index}.mp4"), fourcc, fps, (width, height))
            frame_count = 0

    cap.release()
    out.release()

    print("Videos split successfully!")

# Path for input video on Google Drive
input_video_path = '/content/drive/MyDrive/_edit/12 AL_combined.mp4'

# Split time in minutes and seconds
split_time_minutes = 34
split_time_seconds = 35

# Call the function to split the video
split_video(input_video_path, split_time_minutes, split_time_seconds)

import cv2
import os
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

def split_video(input_path, split_time_minutes, split_time_seconds):
    cap = cv2.VideoCapture(input_path)

    if not cap.isOpened():
        print("Error: Could not open video file.")
        return

    fps = int(cap.get(cv2.CAP_PROP_FPS))
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    fourcc = cv2.VideoWriter_fourcc(*'MP4V')  # Change the codec to MP4V

    output_folder = os.path.dirname(input_path)
    output_file_prefix = os.path.splitext(os.path.basename(input_path))[0]

    split_frame = int((split_time_minutes * 60 + split_time_seconds) * fps)

    frame_count = 0
    output_index = 1

    out = cv2.VideoWriter(os.path.join(output_folder, f"{output_file_prefix}_part{output_index}.mp4"), fourcc, fps, (width, height))

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        frame_count += 1
        out.write(frame)

        if frame_count >= split_frame or frame_count == total_frames:
            out.release()
            output_index += 1
            if frame_count < total_frames:
                out = cv2.VideoWriter(os.path.join(output_folder, f"{output_file_prefix}_part{output_index}.mp4"), fourcc, fps, (width, height))
            frame_count = 0

    cap.release()
    out.release()

    print("Videos split successfully!")

# Path for input video on Google Drive
input_video_path = '/content/drive/MyDrive/_edit/14 RT_combined.mp4'

# Split time in minutes and seconds
split_time_minutes = 13
split_time_seconds = 25

# Call the function to split the video
split_video(input_video_path, split_time_minutes, split_time_seconds)

"""## **Many points. to split**"""

import cv2
import os
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

def split_video(input_path, split_times_minutes, split_times_seconds):
    cap = cv2.VideoCapture(input_path)

    if not cap.isOpened():
        print("Error: Could not open video file.")
        return

    fps = int(cap.get(cv2.CAP_PROP_FPS))
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    fourcc = cv2.VideoWriter_fourcc(*'MP4V')  # Change the codec to MP4V

    output_folder = os.path.dirname(input_path)
    output_file_prefix = os.path.splitext(os.path.basename(input_path))[0]

    frame_count = 0
    output_index = 1

    split_frame_times = [(split_minutes * 60 + split_seconds) * fps for split_minutes, split_seconds in zip(split_times_minutes, split_times_seconds)]

    out = cv2.VideoWriter(os.path.join(output_folder, f"{output_file_prefix}_part{output_index}.mp4"), fourcc, fps, (width, height))

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        frame_count += 1
        out.write(frame)

        if frame_count in split_frame_times or frame_count == total_frames:
            out.release()
            output_index += 1
            if frame_count < total_frames:
                out = cv2.VideoWriter(os.path.join(output_folder, f"{output_file_prefix}_part{output_index}.mp4"), fourcc, fps, (width, height))
            frame_count = 0

    cap.release()
    out.release()

    print("Videos split successfully!")

# Path for input video on Google Drive
input_video_path = '/content/drive/MyDrive/_edit/RT_ El Affroun.mp4'

# Split times in minutes and seconds
split_times_minutes = [16, 22]  # Add the split times you want in minutes
split_times_seconds = [46, 26]  # Add the split times you want in seconds

# Call the function to split the video
split_video(input_video_path, split_times_minutes, split_times_seconds)

import cv2
import os
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

def split_video(input_path, split_times_minutes, split_times_seconds):
    cap = cv2.VideoCapture(input_path)

    if not cap.isOpened():
        print("Error: Could not open video file.")
        return

    fps = int(cap.get(cv2.CAP_PROP_FPS))
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    fourcc = cv2.VideoWriter_fourcc(*'MP4V')  # Change the codec to MP4V

    output_folder = os.path.dirname(input_path)
    output_file_prefix = os.path.splitext(os.path.basename(input_path))[0]

    frame_count = 0
    output_index = 1

    split_frame_times = [(split_minutes * 60 + split_seconds) * fps for split_minutes, split_seconds in zip(split_times_minutes, split_times_seconds)]

    out = cv2.VideoWriter(os.path.join(output_folder, f"{output_file_prefix}_part{output_index}.mp4"), fourcc, fps, (width, height))

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        frame_count += 1
        out.write(frame)

        if frame_count in split_frame_times or frame_count == total_frames:
            out.release()
            output_index += 1
            if frame_count < total_frames:
                out = cv2.VideoWriter(os.path.join(output_folder, f"{output_file_prefix}_part{output_index}.mp4"), fourcc, fps, (width, height))
            frame_count = 0

    cap.release()
    out.release()

    print("Videos split successfully!")

# Path for input video on Google Drive
input_video_path = '/content/drive/MyDrive/_edit/RT_ El Affroun.mp4'

# Split times in minutes and seconds
split_times_minutes = [16, 22]  # Add the split times you want in minutes
split_times_seconds = [46, 26]  # Add the split times you want in seconds

# Call the function to split the video
split_video(input_video_path, split_times_minutes, split_times_seconds)